{
 "title": "COVID-19",
 "time": { "from": "now-15d", "to": "now-1d" },
 "templating": {
  "list": [
   {
    "name": "state",
    "query": "show tag values with key = \"state\""
   },
   {
    "name": "city",
    "query": "show tag values with key = \"city\""
   }
  ]
 },
 "panels": [
  {
   "title": "Total cases",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "periods": 7,
     "query": "select sum(\"cases\") from covid19.autogen.data where state != \"\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "timeshiftUnit": "days"
    }
   ]
  },
  {
   "title": "Cases evolution (log10)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 3, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "periods": 7,
     "query": "select cumulative_sum(sum(\"cases\")) from covid19.autogen.data where $timeFilter and state != \"\" group by time(1d) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "timeshiftUnit": "days"
    }
   ]
  },
  {
   "title": "Cases evolution (linear)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 6, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "periods": 7,
     "query": "select cumulative_sum(sum(\"cases\")) from covid19.autogen.data where $timeFilter and state != \"\" group by time(1d) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "timeshiftUnit": "days"
    }
   ]
  },
  {
   "title": "Cases evolution per state - $state",
   "type": "graph",
   "gridPos": { "h": 12, "w": 4, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "periods": 7,
     "query": "select cumulative_sum(sum(\"cases\")) from covid19.autogen.data where $timeFilter and state =~ /$state/ group by time(1d) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "timeshiftUnit": "days"
    }
   ]
  },
  {
   "title": "Cases per day per state - $state",
   "type": "graph",
   "gridPos": { "h": 12, "w": 4, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "periods": 7,
     "query": "select sum(\"cases\") from covid19.autogen.data where $timeFilter and state =~ /$state/  group by time(1d) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "timeshiftUnit": "days"
    }
   ]
  },
  {
   "title": "Cases per city",
   "type": "table",
   "gridPos": { "h": 12, "w": 5, "x": 0, "y": 3 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "periods": 7,
     "query": "SELECT last(\"count\") FROM covid19.autogen.data WHERE $timeFilter and state != \"\" GROUP BY city, state fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "timeshiftUnit": "days"
    }
   ]
  },
  {
   "title": "Cases/day (log10)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 3, "x": 5, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "periods": 7,
     "query": "select sum(\"cases\") from covid19.autogen.data where $timeFilter and state != \"\" group by time(1d) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "timeshiftUnit": "days"
    }
   ]
  },
  {
   "title": "Cases per day",
   "type": "graph",
   "gridPos": { "h": 12, "w": 6, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "periods": 7,
     "query": "select sum(\"cases\") from covid19.autogen.data where $timeFilter and state != \"\" group by time(1d) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "timeshiftUnit": "days"
    }
   ]
  },
  {
   "title": "Cases evolution per city - $city",
   "type": "graph",
   "gridPos": { "h": 12, "w": 4, "x": 14, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "periods": 7,
     "query": "select cumulative_sum(sum(\"cases\")) from covid19.autogen.data where $timeFilter and city =~ /$city/ group by time(1d) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "timeshiftUnit": "days"
    }
   ]
  },
  {
   "title": "Cases per day per city - $city",
   "type": "graph",
   "gridPos": { "h": 12, "w": 4, "x": 18, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "periods": 7,
     "query": "select sum(\"cases\") from covid19.autogen.data where $timeFilter and city =~ /$city/  group by time(1d) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "timeshiftUnit": "days"
    }
   ]
  },
  {
   "title": "Cases per day",
   "type": "table",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 15 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "periods": 7,
     "query": "select sum(\"cases\") from covid19.autogen.data  where time < now() and state != \"\" group by time(1d)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "timeshiftUnit": "days"
    }
   ]
  }
 ]
}